# Day 2: 1202 Program Alarm

https://adventofcode.com/2019/day/2

# Setup

In [1]:
import numpy as np

## Implementation

In [2]:
with open('input.txt') as f:
    line = f.readline()
CODES = np.array(list(map(int, line.split(','))))

In [3]:
CODES

array([  1,   0,   0,   3,   1,   1,   2,   3,   1,   3,   4,   3,   1,
         5,   0,   3,   2,   6,   1,  19,   1,  19,  10,  23,   2,  13,
        23,  27,   1,   5,  27,  31,   2,   6,  31,  35,   1,   6,  35,
        39,   2,  39,   9,  43,   1,   5,  43,  47,   1,  13,  47,  51,
         1,  10,  51,  55,   2,  55,  10,  59,   2,  10,  59,  63,   1,
         9,  63,  67,   2,  67,  13,  71,   1,  71,   6,  75,   2,   6,
        75,  79,   1,   5,  79,  83,   2,  83,   9,  87,   1,   6,  87,
        91,   2,  91,   6,  95,   1,  95,   6,  99,   2,  99,  13, 103,
         1,   6, 103, 107,   1,   2, 107, 111,   1, 111,   9,   0,  99,
         2,  14,   0,   0])

In [4]:
def step(codes, pos):
    codes = codes.copy()
    op = codes[pos]
    if op == 99:
        return codes, -1
    i1, i2, i3 = codes[pos+1 : pos+4]
    v1, v2 = codes[i1], codes[i2]
    result = v1 + v2 if op == 1 else v1 * v2
    codes[i3] = result
    return codes, pos + 4

In [5]:
def run(code):
    pos = 0
    while pos != -1:
        code, pos = step(code, pos)
    return code

## Tests

In [6]:
test = np.array([
    1,9,10,3,
    2,3,11,0,
    99,
    30,40,50
])

In [7]:
run(test)

array([3500,    9,   10,   70,    2,    3,   11,    0,   99,   30,   40,
         50])

In [8]:
run([1,0,0,0,99])

[2, 0, 0, 0, 99]

In [9]:
run([2,3,0,3,99])

[2, 3, 0, 6, 99]

In [10]:
run([2,4,4,5,99,0])

[2, 4, 4, 5, 99, 9801]

In [11]:
run([1,1,1,4,99,5,6,0,99])

[30, 1, 1, 4, 2, 5, 6, 0, 99]

## Part One

In [12]:
fixed_codes = CODES.copy()
fixed_codes[1] = 12
fixed_codes[2] = 2

In [13]:
run(fixed_codes)

array([4138687,      12,       2,       2,       1,       1,       2,
             3,       1,       3,       4,       3,       1,       5,
             0,       3,       2,       6,       1,      24,       1,
            19,      10,      28,       2,      13,      23,     140,
             1,       5,      27,     141,       2,       6,      31,
           282,       1,       6,      35,     284,       2,      39,
             9,     852,       1,       5,      43,     853,       1,
            13,      47,     858,       1,      10,      51,     862,
             2,      55,      10,    3448,       2,      10,      59,
         13792,       1,       9,      63,   13795,       2,      67,
            13,   68975,       1,      71,       6,   68977,       2,
             6,      75,  137954,       1,       5,      79,  137955,
             2,      83,       9,  413865,       1,       6,      87,
        413867,       2,      91,       6,  827734,       1,      95,
             6,  827

In [14]:
run(fixed_codes)[0]

4138687

## Part Two

In [15]:
def find_noun_verb(codes, target):
    rang = np.arange(100)
    for noun in rang:
        for verb in rang:
            test_code = codes.copy()
            test_code[1] = noun
            test_code[2] = verb
            result = run(test_code)[0]
            if result == target:
                return noun, verb

In [16]:
TARGET = 19690720
noun, verb = find_noun_verb(CODES, TARGET)
print(100 * noun + verb)

6635
