# Day 5: 

https://adventofcode.com/2019/day/5

## Setup

In [1]:
import numpy as np

In [2]:
with open('input/05.txt') as f:
    line = f.readline()
CODES = np.array(list(map(int, line.split(','))))

## Implementation

In [3]:
def split_op_modes(X):
    X, op = divmod(X, 100)
    X, mode1 = divmod(X, 10)
    X, mode2 = divmod(X, 10)
    X, mode3 = divmod(X, 10)
    assert mode3 == 0
    return op, (mode1, mode2, mode3)

def step(codes, pos, input, debug=False):
    
    # TODO: streamline argument fetching?
    
    def get_value(i, mode):
        return i if mode else codes[i]        
    
    op, (mode1, mode2, mode3) = split_op_modes(codes[pos])
    inc = 0
    if op == 99:
        return codes, -1
    elif op in (1, 2):
        i1, i2, i3 = codes[pos+1 : pos+4]
        v1 = get_value(i1, mode1)
        v2 = get_value(i2, mode2)
        result = v1 + v2 if op == 1 else v1 * v2
        codes[i3] = result
        inc = 4
    elif op == 3:
        i = codes[pos+1]
        result = input
        codes[i] = result
        inc = 2
    elif op == 4:
        i = codes[pos+1]
        v = get_value(i, mode1)
        print('*', v)
        inc = 2
    elif op in (5, 6):
        i1, i2 = codes[pos+1 : pos+3]
        v1 = get_value(i1, mode1)
        v2 = get_value(i2, mode2)
        if (not v1) == (op == 6):
            pos = v2
        else:
            inc = 3
    elif op in (7, 8):
        i1, i2, i3 = codes[pos+1 : pos+4]
        v1 = get_value(i1, mode1)
        v2 = get_value(i2, mode2)
        result = 1 * (v1 < v2) if op == 7 else 1 * (v1 == v2)
        codes[i3] = result
        inc = 4
    if debug:
        print('{} ({} {} {}) => pos, inc = {}, {}'.format(
            op, mode1, mode2, mode3, pos, inc), flush=True)
    return codes, pos + inc

def run(code, input, debug=False, imax=1000):
    code = np.array(code).copy()
    pos = 0
    i = 0
    while pos != -1:
        code, pos = step(code, pos, input, debug=debug)
        i += 1
        if i > imax:
            raise RuntimeError('too many iterations')
    return code

##  Tests

In [4]:
run([3,0,4,0,99], 1)

* 1


array([ 1,  0,  4,  0, 99])

In [5]:
run([1002,4,3,4,33], 1)

array([1002,    4,    3,    4,   99])

In [6]:
run([3,9,8,9,10,9,4,9,99,-1,8], input=8)

* 1


array([ 3,  9,  8,  9, 10,  9,  4,  9, 99,  1,  8])

In [7]:
run([3,3,1107,-1,8,3,4,3,99], 7)

* 1


array([   3,    3, 1107,    1,    8,    3,    4,    3,   99])

In [8]:
run([3,12,6,12,15,1,13,14,13,4,13,99,-1,0,1,9], 0)

* 0


array([ 3, 12,  6, 12, 15,  1, 13, 14, 13,  4, 13, 99,  0,  0,  1,  9])

In [9]:
run([3,3,1105,-1,9,1101,0,0,12,4,12,99,1], 0)

* 0


array([   3,    3, 1105,    0,    9, 1101,    0,    0,   12,    4,   12,
         99,    0])

In [10]:
run([3,21,1008,21,8,20,1005,20,22,107,8,21,20,1006,20,31,
1106,0,36,98,0,0,1002,21,125,20,4,20,1105,1,46,104,
999,1105,1,46,1101,1000,1,20,4,20,1105,1,46,98,99], 7)

* 999


array([   3,   21, 1008,   21,    8,   20, 1005,   20,   22,  107,    8,
         21,   20, 1006,   20,   31, 1106,    0,   36,   98,    0,    7,
       1002,   21,  125,   20,    4,   20, 1105,    1,   46,  104,  999,
       1105,    1,   46, 1101, 1000,    1,   20,    4,   20, 1105,    1,
         46,   98,   99])

## Part One

In [11]:
run(CODES, 1);

* 0
* 0
* 0
* 0
* 0
* 0
* 0
* 0
* 0
* 4887191


## Part Two

In [13]:
run(CODES, 5);

* 3419022
